### ISSUE TITLE
Select version?

### ISSUE THREAD

**Issue by P3anutP** [kiraio-moe/LoveLive2D#11]
Sorry if this sounds stupid but i opened the exe file and then opened live2d, and a window popped up with options: the free version or the trial etc.. so i assume i need to choose the trial version and this tool can pass the timelimit? or is this pop-up not supposed to appear in the first place?
and not sure if that's related but when i ran exe it just opened a window then closed by itself.. i didn't get to select a version.

**Comment by kiraio-moe** [comment]
> Sorry if this sounds stupid but i opened the exe file and then opened live2d, and a window popped up with options: the free version or the trial etc.. so i assume i need to choose the trial version and this tool can pass the timelimit? or is this pop-up not supposed to appear in the first place? and not sure if that's related but when i ran exe it just opened a window then closed by itself.. i didn't get to select a version.

Hi, first you need to install Install [.NET 6.0 SDK](https://dotnet.microsoft.com/download/dotnet/6.0 ".NET 6.0 SDK") or [.NET 8.0 SDK](https://dotnet.microsoft.com/download/dotnet/8.0 ".NET 8.0 SDK"). Close any Live2D Cubism instances.
Open LoveLive2D you've downloaded and select `Patch Live2D Cubism Editor...`, choose the Live2D Cubism executable (**not installer**), done!
