### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Eka010101** [kiraio-moe/LoveLive2D#13]
hai, hello I want to ask.... I know I look stupid for asking this but, where's the exe? I tried download it and change the zip into exe but, it didn't work. tried to extrack it, but couldn't find the exe file. sorry if my question sounds stupid

**Comment by kiraio-moe** [comment]
> hai, hello I want to ask.... I know I look stupid for asking this but, where's the exe? I tried download it and change the zip into exe but, it didn't work. tried to extrack it, but couldn't find the exe file. sorry if my question sounds stupid

Hi, you can download LoveLive2D at Releases menu then extract them. From there, you need .NET 6 or .NET 8 SDK's to run the executable.

**Comment by Eka010101** [comment]
alright thank you very much!
