### ISSUE TITLE
Can't select Cubism Editor in Mac

### ISSUE THREAD

**Issue by FrzAdli** [kiraio-moe/LoveLive2D#14]
I'm using mac, and after select patch the editor, I need to select the Cubism Editor executable path, but in mac, the file format is .app so I can't select it. Is there any solution?
![image](https://github.com/user-attachments/assets/5b09e106-5b25-414a-8885-aa8efb62d37f)

**Comment by kiraio-moe** [comment]
> I'm using mac, and after select patch the editor, I need to select the Cubism Editor executable path, but in mac, the file format is .app so I can't select it. Is there any solution? ![image](https://private-user-images.githubusercontent.com/129392638/356856241-5b09e106-5b25-414a-8885-aa8efb62d37f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjU5MjUsIm5iZiI6MTcyMzM2NTYyNSwicGF0aCI6Ii8xMjkzOTI2MzgvMzU2ODU2MjQxLTViMDllMTA2LTViMjUtNDE0YS04ODg1LWFhOGVmYjYyZDM3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwODQwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDlhYTIzYjg1ZmNhODk0ZDMxOGYyMGFiMGQ4MzVkZmQzNTdhYjI1MjdjY2NlNWRlNzZiOThhODQ5MGNlNDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JUwGeWqpxdTZhTYU4OSftShhSIsFIKLlwm2HPHPyT_M)

The file extension isn't important, but the `app` folder. Is it exists?

**Comment by FrzAdli** [comment]
The `app` folder does exist but is inside Cubism Editor.app (right click > show package contents). But since you said its main function was to patch some files in `app/lib`, and I still couldn't select anything from the executables, what I did was manually replace the `rlm1501.jar` file from LoveLive2D, and also replaced `Live2D_Cubism .jar` that I got from my friend who uses LoveLive2D too. Even though it's manual, at least this method works. Thank You

**Comment by kiraio-moe** [comment]
> The `app` folder does exist but is inside Cubism Editor.app (right click > show package contents). But since you said its main function was to patch some files in `app/lib`, and I still couldn't select anything from the executables, what I did was manually replace the `rlm1501.jar` file from LoveLive2D, and also replaced `Live2D_Cubism.jar` that I got from my friend who uses LoveLive2D too. Even though it's manual, at least this method works. Thank You

Your welcome & thanks for the explanation.
Can you share the Live2D `.app` file? I want to know the structure of this file, so maybe in the future i can make LoveLive2D automatically patch them.

**Comment by kiraio-moe** [comment]
> Sorry for the long response, here is the `zip` file of the `.app` file. I put it in the following GDrive link because there is a maximum limit for attaching files https://drive.google.com/file/d/1s7tq0gBr0jdZWjJaM1hAgNbLp3q_wxvm/view?usp=sharing

Thanks.

**Comment by kiraio-moe** [comment]
> Sorry for the long response, here is the `zip` file of the `.app` file. I put it in the following GDrive link because there is a maximum limit for attaching files https://drive.google.com/file/d/1s7tq0gBr0jdZWjJaM1hAgNbLp3q_wxvm/view?usp=sharing

Did you just rename the `.app` to `.zip`? If yes, then the `.app` file is basically a `.zip` file then. I can work with it pretty easily :D
