### ISSUE TITLE
No idea which file to run (MacOs 15 Beta, Intel)

### ISSUE THREAD

**Issue by ThatKoza** [kiraio-moe/LoveLive2D#15]
<img width="696" alt="Screenshot 2024-08-22 at 10 11 00" src="https://github.com/user-attachments/assets/83e48453-7751-43c1-9a51-7dbda9f9aaf6">

<img width="185" alt="Screenshot 2024-08-22 at 10 11 51" src="https://github.com/user-attachments/assets/5099f7a4-e3ca-44e2-8ed4-5e410a789f7c">
I have tried running LoveLive2D blank through the terminal, no outcome. The tutorial itself is made for Windows, so its hard to understand what to do as Mac user. I have .NET SDK 8.0.100 installed, 8.0.0 in another words.
Questions are, do i need to run x file in console and do i need to install .NET 6.0 instead?

**Comment by ThatKoza** [comment]
I have also tried reinstalling .NET and downloading different releases from github, the blank still cannot be recognised as an executable

**Comment by kiraio-moe** [comment]
Nope, just install one of the required .NET version.
Have you ever running a terminal?  If not, Google on how to open a Terminal on the current folder in Mac. The type:

``` bash
./LoveLive2D
```

**Comment by ThatKoza** [comment]
<img width="515" alt="Screenshot 2024-08-24 at 09 43 53" src="https://github.com/user-attachments/assets/03f9dc1a-dc4a-4be7-842c-76c42d66bc5f">
i dont really get it

**Comment by ThatKoza** [comment]
ok, i fixed the error with chmod +x "path name". I have replaced Live2D_Cubism.jar and rlm1501 from the #14 and everything worked

**Comment by kiraio-moe** [comment]
Hi @ThatKoza. I want to know, does the `.app` in Mac is basically a `.zip` file? I didn't have a Max device to check them out.

**Comment by ThatKoza** [comment]
@kiraio-moe technically, no, .app functions as a folder, rather than .zip file. But, as sample, IOS apps, .ipa, work as .zip

**Comment by kiraio-moe** [comment]
> @kiraio-moe technically, no, .app functions as a folder, rather than .zip file. But, as sample, IOS apps, .ipa, work as .zip

But in https://github.com/kiraio-moe/LoveLive2D/issues/14#issue-2459454893 image, it's looks like a file or it's just a folder with a custom icon of the app?

**Comment by ThatKoza** [comment]
<img width="115" alt="Screenshot 2024-08-24 at 14 27 38" src="https://github.com/user-attachments/assets/70ad9340-5c18-481d-bdaa-04e1b61a75d0">
<img width="691" alt="Screenshot 2024-08-24 at 14 27 48" src="https://github.com/user-attachments/assets/12010f07-2591-48f0-a3c7-134b72ca8232">
because when you download live2d from the site, it gives you everything in the actual folder, the folder contains data and the apps themselfs

**Comment by ThatKoza** [comment]
<img width="662" alt="Screenshot 2024-08-24 at 14 31 52" src="https://github.com/user-attachments/assets/70006d8f-ee35-44c6-89ef-434fefcad003">
and to access data of the app itself, its contained in the contents folder with a right click on the .app

**Comment by kiraio-moe** [comment]
> <img alt="Screenshot 2024-08-24 at 14 31 52" width="662" src="https://private-user-images.githubusercontent.com/176430486/361136970-70006d8f-ee35-44c6-89ef-434fefcad003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTk1MDMsIm5iZiI6MTcyNDQ5OTIwMywicGF0aCI6Ii8xNzY0MzA0ODYvMzYxMTM2OTcwLTcwMDA2ZDhmLWVlMzUtNDRjNi04OWVmLTQzNGZlZmNhZDAwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxMTMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjg5MTQ4MmU3MjBmYTIzYmE1ZjgwNjYwYTM3NzdlMWQyNjA2ZjczMjU1ODIyNGQ4ZDgyMTVjNDEwMWZjODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Pe11WgQDu4T4oiBbXobg6rpfCFCx7wKsOii-xpyHYI"> and to access data of the app itself, its contained in the contents folder with a right click on the .app

Can you share the `.app`?

**Comment by ThatKoza** [comment]
[Live2D Cubism Editor 5.0 copy.zip](https://github.com/user-attachments/files/16736413/Live2D.Cubism.Editor.5.0.copy.zip)
there

**Comment by kiraio-moe** [comment]
> [Live2D Cubism Editor 5.0 copy.zip](https://github.com/user-attachments/files/16736413/Live2D.Cubism.Editor.5.0.copy.zip) there

Well, the `.app` is basically a symlink file that point to another folder:
![image](https://github.com/user-attachments/assets/3e6e2a26-dc72-4fb8-9096-aabc0c04a85f)

**Comment by ThatKoza** [comment]
> > [Live2D Cubism Editor 5.0 copy.zip](https://github.com/user-attachments/files/16736413/Live2D.Cubism.Editor.5.0.copy.zip) there
> 
> Well, the `.app` is basically a symlink file that point to another folder: ![image](https://private-user-images.githubusercontent.com/58289710/361137523-3e6e2a26-dc72-4fb8-9096-aabc0c04a85f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDAyMjcsIm5iZiI6MTcyNDQ5OTkyNywicGF0aCI6Ii81ODI4OTcxMC8zNjExMzc1MjMtM2U2ZTJhMjYtZGM3Mi00ZmI4LTkwOTYtYWFiYzBjMDRhODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDExNDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZWMzMmI5Y2MyMDRmZmMxODZmM2MyMzI3Y2UyOTZhMmVjZWY0OGRmYzhkZGVkZjEwZDQyZDYyY2Q5ZjQ0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9DjmDULV88nC33XaEw5c5VGiyTeu2r2CA9LjWK5l4ho)

yup, but somehow, it refuses to redirect to the needed folder to patch when starting LoveLive2D, so it requires manual patching. i would just offer to put my .app to releases while you are fixing stuff, but it still contains some of my model data

**Comment by kiraio-moe** [comment]
@ThatKoza Now, it's support automatic patching for macOS in https://github.com/kiraio-moe/LoveLive2D/commit/c1deb86f5827f8c82c1cc22c4c153a02a49b1010.
