### ISSUE TITLE
there is no exe file

### ISSUE THREAD

**Issue by lovestrucker** [kiraio-moe/LoveLive2D#3]
Uh.. am I missing something here because I can't even run this because there's no .exe file
![Screenshot 2024-07-15 021243](https://github.com/user-attachments/assets/d627c264-df6c-4526-b090-7bc82b5b3b9c)

**Comment by kiraio-moe** [comment]
You're downloading the source code. Download the executables from https://github.com/kiraio-moe/LoveLive2D/releases
![image](https://github.com/user-attachments/assets/ad8084bb-e1df-4c99-b40f-464b81781f27)
