### ISSUE TITLE
7 days pop-up.

### ISSUE THREAD

**Issue by takizoli** [kiraio-moe/LoveLive2D#4]
I followed the instructions you provided and this pop-up appeared:

Using offline is available for 7 days after last online authentication.
If the internet is connected, authentication will be automatically performed when you start the editor.
You can check the offline expiration date offline from the below menu.

Should I be concerned? What happens after 7 days?

**Comment by kiraio-moe** [comment]
No need to worry, the pro license will still be valid after 7 days!
Just ignore the pop up forever.
