### ISSUE TITLE
i dont know where to find the live 2d exe file

### ISSUE THREAD

**Issue by batteryacidsorbet** [kiraio-moe/LoveLive2D#6]
i've tried it by pressing the cubism editor and it just doesn't work, maybe i'm dumb but i don't get it.

**Comment by gaywash** [comment]
hello! i have the same issue. I opened the executable as an administrator, then selected "patch pro license" option, I selected the official "Live2D Editor 5.0" but it gives me an error. I wonder what it is... in advance, thank you for the attention and work.

<img width="671" alt="notttle" src="https://github.com/user-attachments/assets/a2a4291e-0284-47bc-a3c3-6f2ee7be0292">

**Comment by batteryacidsorbet** [comment]
i've selected the cubism editor and the version is 5.0, the error seems to be something to do with a jar.

https://github.com/user-attachments/assets/01d2ba5f-0890-49e4-8043-5b1f26c8f7f0

**Comment by kiraio-moe** [comment]
> i've selected the cubism editor and the version is 5.0, the error seems to be something to do with a jar.
> 
>  Untitled.video.-.Made.with.Clipchamp.1.mp4

Your error is just because the tool didn't run as Admin.

**Comment by kiraio-moe** [comment]
> hello! i have the same issue. I opened the executable as an administrator, then selected "patch pro license" option, I selected the official "Live2D Editor 5.0" but it gives me an error. I wonder what it is... in advance, thank you for the attention and work.
> 
> <img alt="notttle" width="671" src="https://private-user-images.githubusercontent.com/177021182/353474327-a2a4291e-0284-47bc-a3c3-6f2ee7be0292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTMyNDEsIm5iZiI6MTcyMjM1Mjk0MSwicGF0aCI6Ii8xNzcwMjExODIvMzUzNDc0MzI3LWEyYTQyOTFlLTAyODQtNDdiYy1hM2MzLTZmMmVlN2JlMDI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNTIyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjNlMmIxMTRiZTBjYWJkMGUzMzJiNWNjODdhYWE4MjBiNmM3ZGQyZmYzZTE5YzBjNmRlYThmNjEwMWI4NGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n0Tow7MbIM7iSIRGSYFBTBgxgpdfviNlySZyIuv3qWg">

Welp, LoveLive2D can't find the module that handle the license activation. I'll investigate it further.

**Comment by gaywash** [comment]
> > hello! i have the same issue. I opened the executable as an administrator, then selected "patch pro license" option, I selected the official "Live2D Editor 5.0" but it gives me an error. I wonder what it is... in advance, thank you for the attention and work.
> > <img alt="notttle" width="671" src="https://private-user-images.githubusercontent.com/177021182/353474327-a2a4291e-0284-47bc-a3c3-6f2ee7be0292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTMyNDEsIm5iZiI6MTcyMjM1Mjk0MSwicGF0aCI6Ii8xNzcwMjExODIvMzUzNDc0MzI3LWEyYTQyOTFlLTAyODQtNDdiYy1hM2MzLTZmMmVlN2JlMDI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNTIyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjNlMmIxMTRiZTBjYWJkMGUzMzJiNWNjODdhYWE4MjBiNmM3ZGQyZmYzZTE5YzBjNmRlYThmNjEwMWI4NGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n0Tow7MbIM7iSIRGSYFBTBgxgpdfviNlySZyIuv3qWg">
> 
> Welp, LoveLive2D can't find the module that handle the license activation. I'll investigate it further.

ooh, it makes sense. I'll love any further guidance with the investigation, again, thank you!

**Comment by kiraio-moe** [comment]
> > ooh, it makes sense. I'll love any further guidance with the investigation, again, thank you! (I wonder if it has something to do with the jar files, maybe Java? I'll try to update my version of Java...)

Nope, I hardcoded the path to the file that needed to be patched. So, if Live2D Cubism is updated and change that particular file name, this tool will fail.

**Comment by kiraio-moe** [comment]
Fixed in #7, you can now download the latest release @batteryacidsorbet, @gaywash!
