### ISSUE TITLE
patch for v5.1 doesnt work

### ISSUE THREAD

**Issue by miuyenn** [kiraio-moe/LoveLive2D#8]
the v5.0 patch works just fine, but when i try to patch v5.1 and open live2d, it appears like this
![Capture](https://github.com/user-attachments/assets/fd579e68-b3f8-4369-a0b1-dbc6d8ecaceb)

**Comment by kiraio-moe** [comment]
> the v5.0 patch works just fine, but when i try to patch v5.1 and open live2d, it appears like this ![Capture](https://private-user-images.githubusercontent.com/136626241/353876716-fd579e68-b3f8-4369-a0b1-dbc6d8ecaceb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDA0NTksIm5iZiI6MTcyMjQ0MDE1OSwicGF0aCI6Ii8xMzY2MjYyNDEvMzUzODc2NzE2LWZkNTc5ZTY4LWIzZjgtNDM2OS1hMGIxLWRiYzZkOGVjYWNlYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNTM1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTlmYjU0MDFhOWNjNTg4MjRiNmU5YWU3NGRmZmY4YmE2YmIzYzRkOTFiZDI0YWVlMWJlNjk5ZmJjZTdlNTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hnr8rYIVzhdLYV2f2lf2Tmgo8PiuvSPY1pn3VHEvz5A)

The latest only fix the patch for v5.0 (stable), not beta.

**Comment by kiraio-moe** [comment]
Fixed in [16c9d82](https://github.com/kiraio-moe/LoveLive2D/commit/16c9d821e7a53ceae4999e2782211bcb7262bca4) @miuyenn. You can download the latest release now.
